### ISSUE TITLE
What's the modified vit network structure?

### ISSUE THREAD

**Issue by Sur-edge-GNN** [SereneLian/TransGNN-Lung#2]
The current image shape of your paper is (1,1,384,384), but the pytorch-pretrained-vit's input image shape is (1,3,384,384), how should it be modified. Second, what's the number of output feature channel?

**Comment by SereneLian** [comment]
Thanks for you comments. 
We modified the ViT model's inputs channel, for instance https://www.kaggle.com/code/leighplt/pytorch-pre-trained-from-3-channels-to-1/notebook. This is a normal way of using CV field models to medical fields. 
The output feature of ViT is 768, which has already been mentioned in the paper.

**Comment by Sur-edge-GNN** [comment]
Thank you for your reply!
&nbsp;


QQ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月9日(星期四) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SereneLian/TransGNN-Lung] What&#39;s the modified vit network structure? (Issue #2)





 
Thanks for you comments.
 We modified the ViT model's inputs channel, for instance https://www.kaggle.com/code/leighplt/pytorch-pre-trained-from-3-channels-to-1/notebook. This is a normal way of using CV field models to medical fields.
 The output feature of ViT is 768, which has already been mentioned in the paper.

**Comment by SereneLian** [comment]
You are welcome :)
